# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: qwer1234

# Logger Config
logging:
  level:
    com.baomidou.mybatisplus.samples.wrapper: debug